#ifndef	NOTL_VERSION_INCLUDED
#define NOTL_VERSION_INCLUDED

#define MAKE_STR_HELPER(a_str) #a_str
#define MAKE_STR(a_str) MAKE_STR_HELPER(a_str)

#define NOTL_VERSION_MAJOR	1
#define NOTL_VERSION_MINOR	1
#define NOTL_VERSION_PATCH	0
#define NOTL_VERSION_BETA	0
#define NOTL_VERSION_VERSTRING	MAKE_STR(NOTL_VERSION_MAJOR) "." MAKE_STR(NOTL_VERSION_MINOR) "." MAKE_STR(NOTL_VERSION_PATCH) "." MAKE_STR(NOTL_VERSION_BETA)

#endif
