function(set_root_directory)
	set(ROOT_DIR "${PROJECT_SOURCE_DIR}")
	cmake_path(NORMAL_PATH ROOT_DIR)
	if("${ROOT_DIR}" MATCHES "[\\/]$")
		string(LENGTH "${ROOT_DIR}" ROOT_DIR_LENGTH)
		math(EXPR ROOT_DIR_LENGTH "${ROOT_DIR_LENGTH} - 1")
		string(SUBSTRING "${ROOT_DIR}" 0 "${ROOT_DIR_LENGTH}" ROOT_DIR)
	endif()
	set(ROOT_DIR "${ROOT_DIR}" PARENT_SCOPE)
endfunction()
